-- Criar orders de teste sem dependências
INSERT INTO orders (
  id, order_number, status, total, tax_total, table_id, customer_id, 
  user_id, user_name, customer_name, customer_nif, shift_id, notes, 
  payment_method, split_payments, invoice_number, sub_account_name, 
  is_synced_agt, agt_submission_uuid, hash, previous_hash, signature, 
  jws_payload, closed_at, created_at, updated_at
) VALUES 
  (
    gen_random_uuid(), 
    null, 
    'FECHADO', 
    15000, 
    null, 
    null, 
    null, 
    null, 
    null, 
    'Mesa Teste 1', 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    0, 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    NOW(), 
    NOW()
  ),
  (
    gen_random_uuid(), 
    null, 
    'ABERTO', 
    25000, 
    null, 
    null, 
    null, 
    null, 
    null, 
    'Balcão Teste 2', 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    0, 
    null, 
    null, 
    null, 
    null, 
    null, 
    null, 
    NOW(), 
    NOW()
  );
